### ISSUE TITLE
Support Windows

### ISSUE THREAD

**Issue by gallexme** [autumnai/collenchyma#61]
With Cuda 7.0/7.5 i get this error
ollenchyma>cargo test
Running target\debug\backend_specs-5e76dbe75e34191a.exe
`
running 5 tests
test backend_spec::native::it_can_use_ibackend_trait_object ... ok
test backend_spec::native::it_can_create_default_backend ... ok
`
after that backend_specs-randumnumber.exe stopped working
GDB OUTPUT:
`running 5 tests
[New Thread 16076.0x1804]
[New Thread 16076.0x3c24]
[New Thread 16076.0x315c]
[New Thread 16076.0x34c0]
[New Thread 16076.0x32d4]
[New Thread 16076.0x42ec]
[New Thread 16076.0x34e4]
[New Thread 16076.0x2a64]
[New Thread 16076.0xe3c]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 16076.0x34e4]
0x000000000051b670 in cuInit ()`

stackframe:
`
#0  0x000000000051b670 in cuInit ()
#1  0x00000000004874ec in collenchyma::frameworks::cuda::api::driver::utils::API::ffi_init ()

```
at src\frameworks\cuda\api\driver/utils.rs:15
```
#2  0x0000000000472fcb in collenchyma::frameworks::cuda::api::driver::utils::API::init ()

```
at src\frameworks\cuda\api\driver/utils.rs:11
```
#3  0x0000000000472bfd in collenchyma::frameworks::cuda::Cuda.IFramework::new ()

```
at src\frameworks\cuda/mod.rs:46
```
#4  0x0000000000406dfe in backend_specs::backend::IBackend::defaultco::backend::Backend<co::frameworks::cuda::Cuda> () at src/backend.rs:106
#5  0x0000000000406cf0 in backend_specs::backend_spec::cuda::it_can_create_default_backend ()

```
at tests/backend_specs.rs:37
```
#6  0x0000000000429e29 in boxed::F.FnBox$LT$A$GT$::call_box::h809104141212590368 ()
#7  0x000000000042c844 in sys_common::unwind::try::try_fn::h15534802711051563033 ()
#8  0x00000000004c471b in sys_common::unwind::try::inner_try::h3ae51230bca914caH9s ()
#9  0x000000000042cbfb in boxed::F.FnBox$LT$A$GT$::call_box::h11947310459896948609 ()
#10 0x00000000004d522e in sys::thread::Thread::new::thread_start::h24036cb9e2bd1c0fLey ()
#11 0x00007ffcfe848102 in KERNEL32!BaseThreadInitThunk ()

   from C:\WINDOWS\system32\kernel32.dll
#12 0x00007ffd00b0c5b4 in ntdll!RtlUserThreadStart () from C:\WINDOWS\SYSTEM32\ntdll.dll
#13 0x0000000000000000 in ?? ()

Backtrace stopped: previous frame inner to this frame (corrupt stack?)
`

**Comment by gallexme** [comment]
any news on this?

**Comment by bklooste** [comment]
This looks like a cuda / cudnn error since the init call is failing.

Other users of the lib have experienced it as well eg https://github.com/NVIDIA/nccl/issues/8 and may indicate cuda/cudnn is not installed properly . In that case a symlink solved it,
